annotations:
    api-approved.kubernetes.io: https://github.com/kubernetes-sigs/gateway-api/pull/4530
    gateway.networking.k8s.io/bundle-version: v1.5.1
    gateway.networking.k8s.io/channel: standard
    helm.sh/resource-policy: keep
