apiVersion: v2
description: A Helm chart for KubeVirt CRDs
name: kubevirt-crds
sources:
- https://kubevirt.io/
- https://kubevirt.io/user-guide/cluster_admin/installation/
type: application
version: 1.6.0
