apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
    name: cdi
spec:
    config:
        featureGates:
            - HonorWaitForFirstConsumer
    imagePullPolicy: IfNotPresent
    infra:
        nodeSelector: {{ .Values.cdi.infra.nodeSelector | toYaml | nindent 10 }}
        tolerations: {{ .Values.cdi.infra.tolerations | toYaml | nindent 10 }}
    workload:
        nodeSelector: {{ .Values.cdi.workload.nodeSelector | toYaml | nindent 10 }}
