apiVersion: v2
appVersion: v1.6.0
description: A Helm chart for KubeVirt
name: kubevirt
sources:
- https://kubevirt.io/
- https://kubevirt.io/user-guide/cluster_admin/installation/
type: application
version: 1.6.0
