apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
    name: kubevirt
    namespace: {{ .Release.Namespace }}
spec:
    certificateRotateStrategy: {}
    configuration: {{ .Values.kubevirt.configuration | toYaml | nindent 8 }}
    customizeComponents: {}
    imagePullPolicy: IfNotPresent
    workloadUpdateStrategy: {}
