cdi:
    config:
        featureGates:
            - HonorWaitForFirstConsumer
            - WebhookPvcRendering
    infra:
        nodeSelector:
            kubernetes.io/os: linux
        tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
    workload:
        nodeSelector:
            kubernetes.io/os: linux
cdiOperator:
    nodeSelector:
        kubernetes.io/os: linux
    replicas: 1
    tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
