cdi:
    certConfig: {}
    cloneStrategyOverride: ""
    config:
        featureGates:
            - HonorWaitForFirstConsumer
            - WebhookPvcRendering
    customizeComponents: {}
    imagePullPolicy: IfNotPresent
    infra:
        nodeSelector:
            kubernetes.io/os: linux
        tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
    priorityClass: ""
    uninstallStrategy: ""
    workload:
        nodeSelector:
            kubernetes.io/os: linux
cdiOperator:
    env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: v1.63.1
        - name: CONTROLLER_IMAGE
          value: quay.io/kubevirt/cdi-controller:v1.63.1
        - name: IMPORTER_IMAGE
          value: quay.io/kubevirt/cdi-importer:v1.63.1
        - name: CLONER_IMAGE
          value: quay.io/kubevirt/cdi-cloner:v1.63.1
        - name: OVIRT_POPULATOR_IMAGE
          value: quay.io/kubevirt/cdi-importer:v1.63.1
        - name: APISERVER_IMAGE
          value: quay.io/kubevirt/cdi-apiserver:v1.63.1
        - name: UPLOAD_SERVER_IMAGE
          value: quay.io/kubevirt/cdi-uploadserver:v1.63.1
        - name: UPLOAD_PROXY_IMAGE
          value: quay.io/kubevirt/cdi-uploadproxy:v1.63.1
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        - name: MONITORING_NAMESPACE
    nodeSelector:
        kubernetes.io/os: linux
    replicas: 1
    tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
