name: Publish Helm Charts

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.*"
#    paths:
#      - charts/**

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish-chart:
    name: Build and publish Helm Charts

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.4
      - name: Log in to the Container registry
        run: "helm registry login ${{ env.REGISTRY }}/${{ github.actor }}/charter -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Build and publish # replace with pre-built binary
        run: "go run cmd/updater/main.go --mode=publish"
