name: Check and update Charts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update:
    name: Update Helm Charts

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Run # replace with pre-built binary
        run: "go run cmd/updater/main.go --mode=update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
